### ISSUE TITLE
libunrar-js error??  Invalid asm.js: Invalid member of stdlib

### ISSUE THREAD

**Issue by freekoy** [workhorsy/uncompress.js#18] opened 2019-04-22 12:34 UTC
how to use this on Android web browser??
or libunrar-js (how to build wasm version???)

**Comment by workhorsy** [comment] 2019-04-22 14:41
Unfortunately the Android branded web browser that comes with some versions of Android, is missing a ton of standard HTML and JS features. uncompress.js should work on Android using Chrome or Firefox.

**Comment by freekoy** [comment] 2019-04-23 13:31
Can you write a tutorial how to compile into libunrar.js?
There are errors.
```
Invalid asm.js: Invalid member of stdlib
no native wasm Memory in use
Assertion failed: no binaryen method succeeded.
```

**Comment by workhorsy** [comment] 2019-04-24 07:46
Unfortunately I don't have the original Emscripten code to generate the binary from source code. I just used the binaries provided by https://github.com/wcchoi/libunrar-js . I was trying to make a modern version using WebAssembly. It does not yet work correctly. I've been too busy to work on it: https://github.com/workhorsy/unrar.js

**Comment by tnikolai2** [comment] 2020-01-19 14:45
https://github.com/tnikolai2/libunrar-js
I managed to compile new wasm version. Instructions in Readme.md

**Comment by workhorsy** [comment] 2020-06-22 04:16
I'm closing this bug for now, as the problem was caused by the wrong web browser.

**Closed as completed by workhorsy** 2020-06-22 04:16 UTC
